n = input('Digite algo: ')
print('O tipo primitivo do que foi digitado é',type)
print('Só tem espaços?  ', n.isspace())
print('É um número?  ', n.isnumeric())
print('É alfabetico?  ', n.isalpha())
print('É alfanumerico?  ', n.isalnum())
print('Está em letras maiúsculas?  ', n.isupper())
print('Está em letras minúsculas?  ', n.islower())
print('Está Capitalizada?  ', n.istitle())